esphome:
  name: btproxy
  friendly_name: btproxy
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_pwd
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Btproxy Fallback Hotspot"
    password: !secret ap_pwd

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
