substitutions:
  device_id: button2
  device_name: Button 2
  ip_address: !secret button2_ip
  ota_pwd: !secret ota_pwd
  api_key: !secret api_key
  ap_wifi_pwd: !secret ap_pwd


packages:
  shelly_1: !include ./packages/shelly_1button.yaml
  logger: !include ./packages/logger.yaml
