substitutions:
  name: gl-s10-bt-proxy-ceb8ac
  friendly_name: Bluetooth Proxy ceb8ac
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/gl-s10.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_key
