substitutions:
  device_id: kitchen2
  device_name: Kitchen 2
  ip_address: !secret kitchen2_ip
  ota_pwd: !secret ota_pwd
  api_key: !secret api_key
  ap_wifi_pwd: !secret ap_pwd


packages:
  shelly_25: !include ./packages/shelly_25.yaml
  logger: !include ./packages/logger.yaml