substitutions:
  device_id: kitchen3
  device_name: Kitchen 3
  ip_address: !secret kitchen3_ip
  ota_pwd: !secret ota_pwd
  api_key: !secret api_key
  ap_wifi_pwd: !secret ap_pwd


packages:
  shelly_1: !include ./packages/shelly_1.yaml
  logger: !include ./packages/logger.yaml
