substitutions:
  device_id: roller2
  device_name: Roller 2
  ip_address: !secret roller2_ip
  ota_pwd: !secret ota_pwd
  api_key: !secret api_key
  ap_wifi_pwd: !secret ap_pwd


packages:
  shelly_25roller: !include ./packages/shelly_25roller.yaml
  logger: !include ./packages/logger.yaml