substitutions:
  device_id: roller4
  device_name: Roller 4
  ip_address: !secret roller4_ip
  ota_pwd: !secret ota_pwd
  api_key: !secret api_key
  ap_wifi_pwd: !secret ap_pwd


packages:
  shelly_25roller: !include ./packages/shelly_25rollerinverted.yaml
  logger: !include ./packages/logger.yaml