substitutions:
  device_id: storeroom1
  device_name: Storeroom 1
  ip_address: !secret storeroom1_ip
  ota_pwd: !secret ota_pwd
  api_key: !secret api_key
  ap_wifi_pwd: !secret ap_pwd


packages:
  shelly_1: !include ./packages/shelly_1.yaml
  logger: !include ./packages/logger.yaml
