substitutions:
  log_level: debug
  log_baud_rate: '115200'
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ip_subnet: !secret ip_subnet
  ip_gateway: !secret ip_gateway
  flash_write_interval: 10min
  api_key: !secret api_key

esphome:
  name: ${device_id}
  build_path: ./build/${device_id}

${platform}:
  board: ${board}

preferences:
  flash_write_interval: ${flash_write_interval}

api:
  encryption:
    key: ${api_key}

logger:
  level: ${log_level}
  baud_rate: ${log_baud_rate}
  
binary_sensor:
  - platform: status
    name: ${device_name} Status

button:
  - platform: restart
    id: reboot
    name: Restart ${device_name}
    icon: mdi:restart

ota:
  password: ${ota_pwd}

sensor:
  - platform: uptime
    name: ${device_name} Uptime
    icon: mdi:clock-digital
  - platform: wifi_signal
    name: ${device_name} WiFi Signal
    icon: mdi:signal

text_sensor:
  - platform: version
    name: ${device_name} Version
  - platform: wifi_info
    ip_address:
      name: ${device_name} IP Address
      icon: mdi:ip-network
      
time:
  - platform: homeassistant

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: false
  #power_save_mode: none
  manual_ip:
    static_ip: ${ip_address}
    subnet: ${ip_subnet}
    gateway: ${ip_gateway}
    #ap:
     #ssid: ${device_id}
     #password: ${ap_wifi_pwd}

#captive_portal:


#wifi:
  #ssid: ${wifi_ssid}
  #password: ${wifi_password}
  #fast_connect: true
  #power_save_mode: none
  #ap:
    #ssid: ${device_id}

#captive_portal:
