substitutions:
  board: esp01_1m

packages:
  base:   !include device_base_esp8266.yaml
  logger: !include logger.yaml

  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT
    name: '${device_name} Switch 1'
    id: sensorid1
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT
    name: '${device_name} Switch 2'
    id: sensorid2
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT
    name: '${device_name} Switch 3'
    id: sensorid3
    filters:
      - delayed_on_off: 50ms
